
spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pokemon
    username: root
    password: hyoyeon99

#    hikari:
#      connection-timeout: 5000
#      validation-timeout: 1000
#      maximum-pool-size: 30
#      minimum-idle: 2

mybatis:
  mapper-locations: sqlmap/**/*.xml
